# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sis_dist.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esis_dist.proto\",\n\tOnRequest\x12\n\n\x02on\x18\x01 \x01(\x08\x12\x13\n\x0btemperatura\x18\x02 \x01(\x05\"\x19\n\x07OnReply\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t2+\n\x07\x41tuador\x12 \n\x08\x44\x65viceOn\x12\n.OnRequest\x1a\x08.OnReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sis_dist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ONREQUEST']._serialized_start=18
  _globals['_ONREQUEST']._serialized_end=62
  _globals['_ONREPLY']._serialized_start=64
  _globals['_ONREPLY']._serialized_end=89
  _globals['_ATUADOR']._serialized_start=91
  _globals['_ATUADOR']._serialized_end=134
# @@protoc_insertion_point(module_scope)
