# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import sis_dist_pb2 as sis__dist__pb2


class AtuadorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeviceOn = channel.unary_unary(
                '/Atuador/DeviceOn',
                request_serializer=sis__dist__pb2.OnRequest.SerializeToString,
                response_deserializer=sis__dist__pb2.OnReply.FromString,
                )


class AtuadorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeviceOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtuadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeviceOn': grpc.unary_unary_rpc_method_handler(
                    servicer.DeviceOn,
                    request_deserializer=sis__dist__pb2.OnRequest.FromString,
                    response_serializer=sis__dist__pb2.OnReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Atuador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Atuador(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeviceOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Atuador/DeviceOn',
            sis__dist__pb2.OnRequest.SerializeToString,
            sis__dist__pb2.OnReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
